openapi: 3.0.3
info:
  title: Research Platform - Client Portal API
  version: 1.0.0
  description: API for institutional client access to research reports

servers:
  - url: https://portal.example.com/api/v1
    description: Client Portal API

security:
  - BasicAuth: []

paths:
  /auth/login:
    post:
      summary: Authenticate client user
      operationId: login
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [username, password]
              properties:
                username:
                  type: string
                password:
                  type: string
                  format: password
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: integer
                    format: int64
                  client_id:
                    type: integer
                    format: int64
                  subscription_level:
                    type: string
                  permissions:
                    type: array
                    items:
                      type: string
                  session_token:
                    type: string
        '401':
          description: Invalid credentials

  /reports:
    get:
      summary: List available research reports
      operationId: listReports
      parameters:
        - name: company_id
          in: query
          schema:
            type: integer
            format: int64
        - name: sector
          in: query
          schema:
            type: string
        - name: analyst_id
          in: query
          schema:
            type: string
        - name: date_from
          in: query
          schema:
            type: string
            format: date
        - name: date_to
          in: query
          schema:
            type: string
            format: date
        - name: recommendation
          in: query
          schema:
            type: string
            enum: [BUY, HOLD, SELL]
        - name: page
          in: query
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
      responses:
        '200':
          description: List of reports
          content:
            application/json:
              schema:
                type: object
                properties:
                  reports:
                    type: array
                    items:
                      $ref: '#/components/schemas/ReportSummary'
                  pagination:
                    $ref: '#/components/schemas/Pagination'
        '403':
          description: Access denied for subscription level

  /reports/{report_id}:
    get:
      summary: Get specific research report
      operationId: getReport
      parameters:
        - name: report_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: format
          in: query
          schema:
            type: string
            enum: [json, pdf]
            default: json
      responses:
        '200':
          description: Research report
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReportDetail'
            application/pdf:
              schema:
                type: string
                format: binary
        '403':
          description: Access denied
        '404':
          description: Report not found

  /reports/{report_id}/download:
    get:
      summary: Download research report
      operationId: downloadReport
      parameters:
        - name: report_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: format
          in: query
          schema:
            type: string
            enum: [pdf, excel, word]
            default: pdf
      responses:
        '200':
          description: File download
          content:
            application/pdf:
              schema:
                type: string
                format: binary
            application/vnd.openxmlformats-officedocument.spreadsheetml.sheet:
              schema:
                type: string
                format: binary
            application/vnd.openxmlformats-officedocument.wordprocessingml.document:
              schema:
                type: string
                format: binary
          headers:
            Content-Disposition:
              description: Attachment filename
              schema:
                type: string

  /companies:
    get:
      summary: List covered companies
      operationId: listCompanies
      parameters:
        - name: search
          in: query
          schema:
            type: string
        - name: sector
          in: query
          schema:
            type: string
        - name: country
          in: query
          schema:
            type: string
      responses:
        '200':
          description: List of companies
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Company'

  /search:
    get:
      summary: Search reports and content
      operationId: searchReports
      parameters:
        - name: query
          in: query
          required: true
          schema:
            type: string
            minLength: 3
        - name: scope
          in: query
          schema:
            type: string
            enum: [titles, content, all]
            default: all
      responses:
        '200':
          description: Search results
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        report_id:
                          type: integer
                          format: int64
                        title:
                          type: string
                        excerpt:
                          type: string
                        relevance_score:
                          type: number
                          format: float
                  total_results:
                    type: integer

  /user/profile:
    get:
      summary: Get user profile
      operationId: getUserProfile
      responses:
        '200':
          description: User profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

  schemas:
    ReportSummary:
      type: object
      properties:
        report_id:
          type: integer
          format: int64
        title:
          type: string
        company_name:
          type: string
        ticker:
          type: string
        analyst_name:
          type: string
        report_type:
          type: string
        recommendation:
          type: string
        price_target:
          type: number
          format: float
        published_at:
          type: string
          format: date-time
        is_new:
          type: boolean

    ReportDetail:
      type: object
      properties:
        report_id:
          type: integer
          format: int64
        title:
          type: string
        company:
          $ref: '#/components/schemas/Company'
        analyst_id:
          type: string
        analyst_name:
          type: string
        report_type:
          type: string
        investment_thesis:
          type: string
        recommendation:
          type: string
        price_target:
          type: number
          format: float
        risk_rating:
          type: string
        sections:
          type: object
        compliance_disclaimers:
          type: array
          items:
            type: string
        published_at:
          type: string
          format: date-time
        access_level:
          type: string

    Company:
      type: object
      properties:
        company_id:
          type: integer
          format: int64
        name:
          type: string
        ticker:
          type: string
        sector:
          type: string
        country:
          type: string
        latest_report_date:
          type: string
          format: date
        reports_count:
          type: integer

    UserProfile:
      type: object
      properties:
        user_id:
          type: integer
          format: int64
        username:
          type: string
        email:
          type: string
        client_name:
          type: string
        subscription_level:
          type: string
        permissions:
          type: array
          items:
            type: string
        last_login:
          type: string
          format: date-time

    Pagination:
      type: object
      properties:
        current_page:
          type: integer
        per_page:
          type: integer
        total_pages:
          type: integer
        total_items:
          type: integer
        has_next:
          type: boolean
        has_previous:
          type: boolean